apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: video-exporter-hpa
  namesoace: webapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-exporter
  maxReplicas: 10
  minReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70